# Generated by Django 4.1.1 on 2022-10-05 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Perfil",
        ),
        migrations.RenameField(
            model_name="perfil",
            old_name="image",
            new_name="imagen",
        ),
        migrations.RenameField(
            model_name="perfil",
            old_name="user",
            new_name="usuario",
        ),
    ]
