# Generated by Django 4.1.1 on 2022-09-21 19:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
                ("fecha_eliminacion", models.DateField(auto_now=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Escritor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
                ("fecha_eliminacion", models.DateField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150)),
                ("descripcion", models.TextField()),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogapp.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "escritor",
                "verbose_name_plural": "escritores",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
                ("fecha_eliminacion", models.DateField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField()),
                ("descripcion", ckeditor.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
                ("fecha_eliminacion", models.DateField(auto_now=True)),
                ("titulo", models.CharField(max_length=50, unique=True)),
                ("subtitulo", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField()),
                ("content", ckeditor.fields.RichTextField()),
                ("imagen_post", models.ImageField(upload_to="images/")),
                ("publicar", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogapp.category",
                    ),
                ),
                (
                    "escritor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogapp.escritor",
                    ),
                ),
                (
                    "me_gusta",
                    models.ManyToManyField(
                        related_name="blogpost_me_gusta", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("tag", models.ManyToManyField(to="blogapp.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
                ("fecha_eliminacion", models.DateField(auto_now=True)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blogapp.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
