# Generated by Django 4.1.1 on 2022-09-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_category_escritor_tag_post_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogCategory",
        ),
        migrations.DeleteModel(
            name="BlogComment",
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.DeleteModel(
            name="BlogTag",
        ),
    ]
