# Generated by Django 4.1.1 on 2022-09-21 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0004_alter_post_me_gusta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="me_gusta",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="blogpost_me_gusta",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(blank=True, null=True, to="blogapp.tag"),
        ),
    ]
