# Generated by Django 4.1.1 on 2022-09-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_alter_post_me_gusta_alter_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
