# Generated by Django 4.1.1 on 2022-09-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0008_alter_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="imagen_categoria",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="comment",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="escritor",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="titulo",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
