# Generated by Django 4.1.1 on 2022-09-24 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0009_category_estado_category_imagen_categoria_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("fecha_creacion",)},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="contenido",
        ),
        migrations.RemoveField(
            model_name="post",
            name="me_gusta",
        ),
        migrations.AddField(
            model_name="comment",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="blogapp.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blogapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="escritor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blogapp.escritor",
            ),
        ),
    ]
