# Generated by Django 4.1.1 on 2022-09-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0010_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="padre",
        ),
    ]
