# Generated by Django 4.1.1 on 2022-09-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0011_remove_comment_autor_remove_comment_padre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="contenido",
            field=models.TextField(),
        ),
    ]
