# Generated by Django 4.1.1 on 2022-09-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0013_comment_autor_alter_comment_contenido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
