# Generated by Django 4.1.1 on 2022-09-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0015_alter_comment_contenido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="imagen_post",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
