# Generated by Django 4.1.1 on 2022-10-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mensajes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mensajes",
            old_name="body",
            new_name="cuerpo",
        ),
        migrations.RenameField(
            model_name="mensajes",
            old_name="sender",
            new_name="enviado_por",
        ),
        migrations.RenameField(
            model_name="mensajes",
            old_name="receiver",
            new_name="recibido_por",
        ),
    ]
